### ISSUE TITLE
spiceypy 2.2.0 released

### ISSUE THREAD

**Issue by AndrewAnnex** [conda-forge/spiceypy-feedstock#10]
I should read up on how to do the version bump but the patches that are applied make this not "push-button", adding the steps needed would be a great addition (is it just the meta.yaml?)

**Comment by Juanlu001** [comment]
@AndrewAnnex for other projects there's a bot that sends a PR automatically after release. On the other hand, apart from the `meta.yaml` the patches might need to be regenerated. We can wait some minutes and, if the bot does not appear, document the steps and do the upgrade ourselves.

**Comment by Juanlu001** [comment]
The patches didn't apply: https://github.com/conda-forge/spiceypy-feedstock/pull/11

**Comment by mariusvniekerk** [comment]
The patches need to be regenerated

**Comment by AndrewAnnex** [comment]
@Juanlu001 do you have time to look into this? I can maybe do it in a few days if you can explain a bit about how to regenerate the patches...

**Comment by Juanlu001** [comment]
On it!

**Comment by Juanlu001** [comment]
For future reference: the patches come from https://github.com/Juanlu001/SpiceyPy/compare/master...simplify-setup-220

**Comment by Juanlu001** [comment]
Done, sorry for the delay! I misremembered the process as much more complicated, but it was just a rebase, a silly git conflict, and that's it. Please test the release and ping me if there are any errors.
