### ISSUE TITLE
update to 2.1.2

### ISSUE THREAD

**Issue by AndrewAnnex** [conda-forge/spiceypy-feedstock#5]
I just released 2.1.1, and I need a bit of a break from CI services 😉 , so I will contribute by posting this issue.

**Comment by Juanlu001** [comment]
:smile: I think the conda-forge automation did almost all of the hard work! #6

**Comment by Juanlu001** [comment]
Sorry, I'm a bit behind with the patches. Now we should focus on 2.1.2 directly.

**Comment by Juanlu001** [comment]
I finally merged the changes, so closing this. If we find problems, let's open a new issue.
